import 'package:get/route_manager.dart';
import 'package:get/get.dart';

class Localstring extends Translations {
  List<String> rtlLanguages = <String>['en'];
  Map<String, Map<String, String>> get keys => {
        'en': {
          "Hello": "Hello! ",
          "Welcome": "Welcome!",
          "PhoneNumber": "Phone Number",
          "Loginlabel": "Phone Number/ Email/ Username",
          "name": "Name",
          "usernamee": "Username",
          "usernamelabel": "Enter Username",
          "namelabel": "Enter Name",
          "retry": "Retry",
          'already_have_acc_txt':"Already have an account? ",
          'dont_have_acc_txt':"Don't have an account? ",
          "Loginmsg":
              "Log in or create an account to start our Steam House Service!",
          "+91": "+91",
          "Password": "Password",
          "Validationtxt": "Please enter password",
          "enterloginlabel": "Enter Phone Number/ Email/ Username",
          "enterpassword": "Enter Password",
          "login": "Login",
          "signup": "Sign Up",
          "settingtxt": "Settings",
          "edit_Profilext": "Edit Profile",
          "Profile": "Profile",
          "complaintxt": "Complain",
          "ServiceRequesttxt": "Service Request",
          "push_Notificationxt": "Push Notification",
          "Contactustxt": "Contact Us",
          "addemptxt": "Add Emp",
          "raisecomplaintxt": "Raise Service Request",
          "logouttxt": "Log Out",
          "hometxt": "Home",
          "steamhousetxt": "Steam House",
          "pressuretxt": "PRESSURE",
          "tempraturetxt": "TEMPRATURE",
          "flowtxt": "FLOW",
          "totalizertxt": "TOTALIZER",
          "homemsgtxt": "This Data May not be accurate",
          "helplinetxt": "Helpline",
          "companynametxt": "Company Name",
          "EnterCompanyNametxt": "Request Subject Title",
          "clickpicturetxt": "Add Image",
          "selectphototxt": "Select OR Click Photo",
          "contactpersontxt": "Contact Number",
          "sendtxt": "Send",
          "submit": "Submit",
          "complainhint": "Description",
          "Searchtxt": "Search",
          "Completed": "Completed",
          "ComplainDetail": "Service Request Detail",
          "Address": "Address",
          "Issue": "Issue",
          "CompanyList": "Company List",
          "company": "Company",
          "Review": "Feedback",
          "Reviewtxt": "Review",
          "Error": "Error",
          "Successfull": "Successfull",
          "requesttitle": " Request Title",
          "requestsubjecttitle": "Request Subject Title",
          "Inprocess": "In-Process",
          "Pending": "Pending",
          "Assigned": "Assigned",
          "employeelist": "Employee List",
          "selectemployee": "Select Employee",
          "Allocation": "Allocation",
          "selecttxt": "Select",
          "Trackmsg": "Tracking Work Status Details",
          "ServiceRequeststatus": "Service Request status",
          "trackingstatus": "Tracking Status",
          "track": "Track Service Request",
          "Assignmanger": "Pending for Assignment",
          "Acceptservice": "Accepted Service Request",
          "AssignEngineer": "Assign To Engineer",
          "Allocatedtechnician ": "Allocated Your work to technician",
          "EngineerCheckIn": "Engineer Check-In",
          "EngineerReviewing": "Engineer Reviewing",
          "workinprogress": "work in progress",
          "EngineerCheckOut": "Engineer Check-Out",
          "WorkCompletedEngineer": "Work Completed by Engineer",
          "VerificationPending": "Verification Pending",
          "VerifiedManager": "Verified by Manager",
          "TicketClose": "Ticket Close",
          "AETHER": "AETHER",
          "WriteComment": "Write Comment...",
          "sharefeedbackmsg": "Please share your Feedback...",
          "Closeticket": "Close Ticket",
          "remark": "Remark",
          "WorkCompletedbyTechnician": "Resolved by Engineer",
          "EngineersDetails": "Engineers Details",
          "RaiseComplain": "Raise Complain",
          "RaiseRequest": "Raise Request",
          "RaiseserviceRequest": "Raise Service Request",
          "livesteam": "Live Data",
          "checkin": "Check - In",
          "workcomplete": "Work Completed",
          "NotGetOtp": "Don’t Get Otp?",
          "Otpmsg": "Enter your OTP code here",
          "Done": "Done",
          "techniciandetail": "Technician Detail",
          "RequestAssignTo": "Assign Request To",
          "Attendedby": "Attended by",
          "AssignRequest": "Assign Request",
          "Resolved": "Resolved",
          "nodata": "No Data Found",
          "CustomerName": "Customer Name",
          "flow": "Flow",
          "Pressure": "Pressure",
          "Temperature": "Temperature",
          "Totalizer": "Totalizer",
          "LastPendingTime": "Last Pending Time",
          "otp": "OTP",
          "Open": "Open",
          "Closed": "Closed",
          "serviceinprocess": "Service in Process",
          "Assignto": "Assign To",
          "Imguploadmsg": "You can Upload Maximum 3 images",
          "LiveSteamTxt": "Live Steam Status",
          "tkt": "#Tkt ",
          "nointernetmsg": "Internet Not Available",
          "editprofile": "Edit Profile",
          "username": "User Name",
          "mobileno": "Mobile no",
          "email": "Email",
          "oldpass": "Old password",
          "oldpasshint": "Enter Old password",
          "confirmpass": "Confirm password",
          "reenterpasshint": "Re-enter New password",
          "newpass": "New password",
          "newpasshint": "Enter New password",
          "changepassword": "Change password",
          "address": "Address",
          "save": "Save",
          "selectdate": "Select Date",
          "selecttime": "Select Time",
        },
      };
}
